"""Harden backend schema and ownership

Revision ID: 58228b117fe8
Revises: 6b09058ce8d7
Create Date: 2026-04-12 23:01:45.594479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58228b117fe8'
down_revision = '6b09058ce8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_check_constraint('ck_accounts_opening_balance', 'opening_balance >= 0')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_check_constraint('ck_categories_kind_allowed', "kind IN ('income', 'expense')")

    with op.batch_alter_table('transaction_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_check_constraint('ck_transactions_type_allowed', "transaction_type IN ('income', 'expense', 'transfer')")
        batch_op.create_index('ix_transactions_user_occurred_on', ['user_id', 'occurred_on'], unique=False)

    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE users SET is_active = 1 WHERE is_active IS NULL")
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active', existing_type=sa.Boolean(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_user_occurred_on')
        batch_op.drop_constraint('ck_transactions_type_allowed', type_='check')

    with op.batch_alter_table('transaction_tags', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('ck_categories_kind_allowed', type_='check')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint('ck_accounts_opening_balance', type_='check')

    # ### end Alembic commands ###
